name: Generate MSYS2 Environment

on: [push, pull_request, workflow_dispatch]
#   push:
#   schedule:
#     - cron: '0 0 * * *'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - name: Install MSYS2 & Dependencies
      run: |
        choco install msys2 --no-progress
        C:\tools\msys64\usr\bin\bash -eo pipefail -lc "\
        pacman --needed --noconfirm -S git make cmake bison flex mingw-w64-x86_64-{llvm,clang,lld} && \
        pacman -Scc --noconfirm \
        "
    - name: Compress MSYS2 Environment
      id: compress
      run: |
        $asset="msys64.7z"
        7z a -bd $asset C:\tools\msys64\
        echo "::set-output name=asset::$asset"
    - name: Define Build Tag
      if: github.event_name == 'push'
      id: build_tag
      run: echo "::set-output name=BUILD_TAG::v$(Get-Date -Format yyMMddHHmmss)"
    - name: Create Release
      if: github.event_name == 'push'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.build_tag.outputs.BUILD_TAG }}
        release_name: ${{ steps.build_tag.outputs.BUILD_TAG }}
    - name: Upload Release Assets
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.compress.outputs.asset }}
        asset_name: ${{ steps.compress.outputs.asset }}
        asset_content_type: application/zip
