name: Generate MSYS2 Environment

on: [push, pull_request, workflow_dispatch]
#   push:
#   schedule:
#     - cron: '0 0 * * *'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - name: Install MSYS2 & Dependencies
      run: |
        choco install msys2 --no-progress
        C:\tools\msys64\usr\bin\bash -eo pipefail -lc "\
        pacman --needed --noconfirm -S git make cmake pkgconf bison flex mingw-w64-x86_64-{llvm,clang,lld} && \
        pacman -Scc --noconfirm \
        "
    - name: Compress MSYS2 Environment
      id: compress
      run: |
        $asset="msys64.7z"
        7z a -bd $asset C:\tools\msys64\
        echo "asset=${asset}" >> $env:GITHUB_OUTPUT
    - name: Define Build Tag
      if: github.event_name == 'push'
      id: build_tag
      run: echo "BUILD_TAG=v$(Get-Date -Format yyMMddHHmmss)" >> $env:GITHUB_OUTPUT
    - name: Publish Release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.build_tag.outputs.BUILD_TAG }}
        name: ${{ steps.build_tag.outputs.BUILD_TAG }}
        prerelease: false
        draft: false
        files: ${{ steps.compress.outputs.asset }}
